language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
sudo: required
dist: trusty
addons:
  apt:
     packages:
        - libglew-dev
        - freeglut3-dev
        - libxi-dev
        - libxmu-dev
        - xserver-xorg-video-dummy
        - xpra
        - xorg-dev
        - opencl-headers
        - libgl1-mesa-dev
        - libxcursor-dev
        - libpulse-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxv-dev
        - libasound2-dev
        - libudev-dev
        - mesa-utils
        - libgl1-mesa-glx
before_install:
  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
  - sudo apt-get update -qq -y
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev xvfb
  - sudo apt-get -yq --force-yes install xserver-xorg-video-vmware-lts-trusty
  - sudo apt-get -yq --force-yes install git-core
  - sudo apt-get -yq --force-yes install automake libtool libpthread-stubs0-dev
  - sudo apt-get -yq --force-yes install xserver-xorg-dev x11proto-xinerama-dev libx11-xcb-dev
  - sudo apt-get -yq --force-yes install libxcb-glx0-dev libxrender-dev
  - sudo apt-get -y install linux-headers-$(uname -r) xutils-dev
  - sudo apt-get -yq --force-yes build-dep libgl1-mesa-dri libxcb-glx0-dev
  - pip install --user mako
  - export TOP=$PWD
  - git clone git://anongit.freedesktop.org/git/mesa/mesa
  - git clone git://anongit.freedesktop.org/git/mesa/vmwgfx
  - git clone git://anongit.freedesktop.org/git/mesa/drm
  - git clone git://anongit.freedesktop.org/git/xorg/driver/xf86-video-vmware
  - export LIBDIR=/usr/lib/x86_64-linux-gnu
  - cd $TOP/drm
  - ./autogen.sh --prefix=/usr --libdir=${LIBDIR}
  - make
  - sudo make install
  - cd $TOP/mesa
  - ./autogen.sh --prefix=/usr --libdir=${LIBDIR} --with-gallium-drivers=svga,swrast --enable-xa --disable-dri --enable-xlib-glx --with-llvm-prefix=/usr/local/bin
  - ./autogen.sh --prefix=/usr --libdir=${LIBDIR} --with-gallium-drivers=svga --with-dri-drivers=swrast --enable-xa --disable-dri3 --enable-glx-tls --with-llvm-prefix=/usr/local/bin
  - make
  - sudo make install
  - cd $TOP/xf86-video-vmware
  - ./autogen.sh --prefix=/usr --libdir=${LIBDIR}
  - make
  - sudo make install
  - cd $TOP/vmwgfx
  - make
  - sudo make install
  - sudo depmod -a
  - sudo update-initramfs -u
  - echo vmwgfx | sudo tee -a /etc/modules
  - find /lib/modules -name vmwgfx.ko -exec ls -l '{}' \;
  - sudo modprobe vmwgfx
  - cd $TOP
before_script:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
#  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
  - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
  - sleep 3
  - LIBGL_ALWAYS_SOFTWARE=1 glxinfo
  - glxinfo
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - LIBGL_ALWAYS_SOFTWARE=1 julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("GLFW"); Pkg.test("GLFW"; coverage=true)'
