author = ["Jay Petacat <jay@jayschwa.net>", "Simon Danisch <sdanisch@gmail.com>"]
name = "GLFW"
uuid = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
version = "3.4.5"

[deps]
GLFW_jll = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"

[compat]
GLFW_jll = "3.4"
julia = "1.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
